require("franjf.dashboard")
require("franjf.telescope")
require("franjf.lualine")
require("franjf.icons")
require("franjf.lsp")
require("franjf.compe")
require("franjf.treesitter")
require("franjf.comments")
